version: 2
updates:
  - package-ecosystem: npm
    directory: /sheger-mobile
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /sheger-admin
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
